### ISSUE TITLE
[BUG] 搜索特定关键词时崩溃

### ISSUE THREAD

**Issue by kagg886** [kagg886/Pixiv-MultiPlatform#6]
- [x] 我使用的是最新版的`Pixiv-MultiPlatform`
- [x] 我保证我能稳定复现这个故障
- [x] 我保证在开发者回复issue时可以在第一时间知悉

# 1. BUG描述
程序崩溃

# 2. 如何复现
1. 搜索`呆猫`
2. 前往作者页面

# 3. 报错堆栈

```text
java.lang.IllegalArgumentException: Key "12337038" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at F0.A.K(SourceFile:160)
	at F0.A$c.Q0(SourceFile:3)
	at C.x.A1(SourceFile:36)
	at B.u.d(SourceFile:15)
	at B.u.e(SourceFile:9)
	at B.r.e(SourceFile:26)
	at B.p$b.b(SourceFile:517)
	at B.p$b.l(SourceFile:9)
	at C.v$a$b.b(SourceFile:14)
	at C.v$a$b.l(SourceFile:9)
	at F0.A$d.h(SourceFile:113)
	at H0.w.y(SourceFile:73)
	at androidx.compose.ui.graphics.e.b(SourceFile:1)
	at H0.C.y(SourceFile:41)
	at androidx.compose.foundation.layout.q.b(SourceFile:33)
	at H0.C.y(SourceFile:41)
	at H0.L$d.b(SourceFile:13)
	at H0.L$d.a(SourceFile:1)
	at h0.k$a.h(SourceFile:69)
	at h0.u$a.i(SourceFile:46)
	at h0.u.o(SourceFile:96)
	at H0.o0.i(SourceFile:3)
	at H0.o0.g(SourceFile:17)
	at H0.L.U(SourceFile:40)
	at H0.L.h(SourceFile:1)
	at H0.L$b.Y1(SourceFile:146)
	at H0.L$b.y(SourceFile:60)
	at androidx.compose.foundation.layout.g.h(SourceFile:202)
	at H0.w.y(SourceFile:73)
	at androidx.compose.foundation.layout.i.b(SourceFile:99)
	at H0.C.y(SourceFile:41)
	at H0.L$d.b(SourceFile:13)
	at H0.L$d.a(SourceFile:1)
	at h0.k$a.h(SourceFile:69)
	at h0.u$a.i(SourceFile:46)
	at h0.u.o(SourceFile:96)
	at H0.o0.i(SourceFile:3)
	at H0.o0.g(SourceFile:17)
	at H0.L.U(SourceFile:40)
	at H0.L.h(SourceFile:1)
	at H0.L$b.Y1(SourceFile:146)
	at H0.L$b.y(SourceFile:60)
	at C.x.A1(SourceFile:58)
	at E.s.g(SourceFile:8)
	at E.s.h(SourceFile:19)
	at E.t$a.b(SourceFile:428)
	at E.t$a.l(SourceFile:9)
	at C.v$a$b.b(SourceFile:14)
	at C.v$a$b.l(SourceFile:9)
	at F0.A$d.h(SourceFile:113)
	at H0.w.y(SourceFile:73)
	at androidx.compose.ui.graphics.e.b(SourceFile:1)
	at H0.C.y(SourceFile:41)
	at H0.L$d.b(SourceFile:13)
	at H0.L$d.a(SourceFile:1)
	at h0.k$a.h(SourceFile:130)
	at h0.u$a.i(SourceFile:46)
	at h0.u.o(SourceFile:96)
	at H0.o0.i(SourceFile:3)
	at H0.o0.g(SourceFile:17)
	at H0.L.U(SourceFile:40)
	at H0.L.h(SourceFile:1)
	at H0.L$b.Y1(SourceFile:146)
	at H0.G.k1(SourceFile:20)
	at H0.G.l1(SourceFile:11)
	at H0.S.f(SourceFile:10)
	at H0.S.x(SourceFile:106)
	at H0.S.y(SourceFile:12)
	at H0.S.r(SourceFile:96)
	at androidx.compose.ui.platform.r.a(SourceFile:33)
	at H0.m0.l(SourceFile:8)
	at androidx.compose.ui.platform.r.dispatchDraw(SourceFile:17)
	at android.view.View.draw(View.java:23628)
	at android.view.View.updateDisplayListIfDirty(View.java:22415)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4631)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4604)
	at android.view.View.updateDisplayListIfDirty(View.java:22345)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4631)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4604)
	at android.view.View.updateDisplayListIfDirty(View.java:22345)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4631)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4604)
	at android.view.View.updateDisplayListIfDirty(View.java:22345)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4631)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4604)
	at android.view.View.updateDisplayListIfDirty(View.java:22345)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5140)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4829)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3987)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2674)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9867)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1431)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1439)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1048)
	at android.view.Choreographer.doFrame(Choreographer.java:943)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1407)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at top.kagg886.pmf.PMFApplication.d(SourceFile:1)
	at top.kagg886.pmf.PMFApplication.b(SourceFile:1)
	at z7.O.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8348)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

**Comment by KTG-suger** [comment]
测了下应该不是特定词搜索的问题，而是只要搜索切到作者，就会崩溃。

另外新版本更新以后，总感觉直连打开图变慢了好多。应该不是我的错觉吧。

**Comment by kagg886** [comment]
> 测了下应该不是特定词搜索的问题，而是只要搜索切到作者，就会崩溃。
> 
> 另外新版本更新以后，总感觉直连打开图变慢了好多。应该不是我的错觉，我特意重装了142版本，体感确实打开速度要比新版本快。
> 图片传不上去，尴尬。描述一下143版本打开之后首页图片会有一个圈在加载，一段时间圈直接消失也不显示图片。卸载重装回142版本没这个问题。

糟了，明天修(x
~~明天期末考试(✓~~

**Comment by kagg886** [comment]
> 测了下应该不是特定词搜索的问题，而是只要搜索切到作者，就会崩溃。
> 
> 另外新版本更新以后，总感觉直连打开图变慢了好多。应该不是我的错觉，我特意重装了142版本，体感确实打开速度要比新版本快。 图片传不上去，尴尬。描述一下143版本打开之后首页图片会有一个圈在加载，一段时间圈直接消失也不显示图片。卸载重装回142版本没这个问题。

经测试发现：
1. 变灰的原因是因为加载时间超时导致图片不能被全部读取，已延长timeout时间
2. 变慢的原因是忽略了ssl证书导致的，已将最新版的逻辑改为检测到piximg代理被更换时才忽略ssl
3. 搜索闪退的原因见[https://github.com/kagg886/Pixko/commit/0973437a0dd385be8258c4d209bb0c283bd567f8](https://github.com/kagg886/Pixko/commit/0973437a0dd385be8258c4d209bb0c283bd567f8)

**Comment by KTG-suger** [comment]
> > 测了下应该不是特定词搜索的问题，而是只要搜索切到作者，就会崩溃。
> > 另外新版本更新以后，总感觉直连打开图变慢了好多。应该不是我的错觉，我特意重装了142版本，体感确实打开速度要比新版本快。
> > 图片传不上去，尴尬。描述一下143版本打开之后首页图片会有一个圈在加载，一段时间圈直接消失也不显示图片。卸载重装回142版本没这个问题。
> 
> 糟了，明天修(x ~明天期末考试(✓~
> 
> 1. 临时解决方案是挂梯子，不知道为什么sni爆了
> 2. 建议给个扣扣联系方式我好把测试包发你看看(

扣扣：10063666
我应该中午和晚上都有空

**Comment by kagg886** [comment]
![image](https://github.com/user-attachments/assets/9b1da44a-95a4-48ea-a642-6c2829841f15)
以后有事在扣扣说吧.gif
